Add a new html chat page with a hello message from server
ESaracay/my-portfolio pull request #6
Opened 2020-06-29 21:32 UTC by ESaracay

Week-3 chat implementation

2020-06-29 21:59 UTC, zmr approved these changes

2020-06-30 13:04 UTC, tylerhou commented on portfolio/src/main/webapp/script.js
> +  if(text.txt != null) {
`if (`

2020-06-30 13:04 UTC, tylerhou commented on portfolio/src/main/webapp/script.js
> +    const name = await server.text();
Include a failure case?

2020-06-30 21:03 UTC, tylerhou requested changes

2020-06-30 21:03 UTC, tylerhou commented on portfolio/src/main/webapp/script.js
> +        console.log("User:"+comments[i]["user"]);
Please format this section; in particular there should be spaces around every `+`.

2020-06-30 21:03 UTC, tylerhou commented on portfolio/src/main/webapp/script.js
> +    console.log(comments);
It's a good idea to remove console.logs so the end user doesn't see them.

If you really need debugging statements to stay around, I would define a function:

```js
function LOG() {
    if (false) {
        console.log.apply(console, arguments);
    }
}
```

Use it like `LOG("List of words: ", words)`.

Then in development you can change the hardcoded false to true.

2020-06-30 21:03 UTC, tylerhou commented on walkthroughs/week-3-server/examples/random-quotes/server-stats/src/main/java/com/google/sps/servlets/ServerStatsServlet.java
> +  private String convertToJson(ServerStats serverStats) {
It's probably better to use Gson, but this works for now. JSON serialization is pretty tricky if you have to serialize objects with arbitrary strings.

I would add a TODO:

```
// TODO(esaracay): Use GSON to serialize.
String json = "{";
```

2020-06-30 21:03 UTC, tylerhou commented on walkthroughs/week-3-server/examples/random-quotes/server-stats/src/main/webapp/script.js
> +/** Creates an <li> element containing text. */
Quality JSDocs.

2020-06-30 22:02 UTC, merged